services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: shuttlecall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shuttlecall_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3016:3016"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:shuttlecall_pass@db:5432/shuttlecall?schema=public"
      NEXTAUTH_SECRET: "shuttlecall-dev-secret-change-in-production-32chars"
      NEXTAUTH_URL: "https://shuttle.erkanerdem.online"
      NEXT_PUBLIC_APP_NAME: "ShuttleCall"
      NEXT_PUBLIC_APP_URL: "https://shuttle.erkanerdem.online"
      NODE_ENV: "production"
      FIREBASE_PROJECT_ID: "shuttlecall-44dd8"
      FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@shuttlecall-44dd8.iam.gserviceaccount.com"
      FIREBASE_PRIVATE_KEY: ""
      VAPID_PUBLIC_KEY: "BNHTeNNDT9nyGap4mQIjsU-gO5qRtjYAHzI9uXZSdOUWvp-_9d5HhSDYHWDFaFUOn0QsmAhyC2xOJt4BWglvZqg"
      VAPID_PRIVATE_KEY: "y659BsZ5DOjWuUIHVTe4nxxHMBezODSGC-pEhKfbyHQ"
      VAPID_CONTACT_EMAIL: "mailto:admin@shuttlecall.com"
    volumes:
      - uploads:/app/public/images/locations

volumes:
  pgdata:
  uploads:
